upstream puma {
  server unix:///var/www/k5/tmp/sockets/puma.sock;
}

server {
  listen 80;
  server_name _;  # ← サーバーのIPまたはドメインに変更

  root /var/www/k5/public;
  access_log /var/log/nginx/k5_access.log;
  error_log  /var/log/nginx/k5_error.log;

  client_max_body_size 10m;

  # アセットは Nginx が直接配信
  location ^~ /assets/ {
    gzip_static on;
    expires max;
    add_header Cache-Control public;
  }

  # その他のリクエストは Puma へ
  location / {
    proxy_pass http://puma;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $http_host;
    proxy_redirect off;
  }

  error_page 500 502 503 504 /500.html;
  keepalive_timeout 10;
}
